# Generated by Django 3.1.7 on 2021-03-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgs',
            field=models.ImageField(default='', max_length=400, upload_to='Product_imgs/'),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='profile',
            field=models.ImageField(default='', max_length=400, upload_to='UserProfile/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile',
            field=models.ImageField(default='', max_length=400, upload_to='VenderProfile/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_image',
            field=models.ImageField(default='', max_length=400, upload_to='Product_Cat/'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Sc_image',
            field=models.ImageField(default='', max_length=400, upload_to='Product_sub_cat'),
        ),
    ]
