# Generated by Django 3.1.7 on 2021-03-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20210320_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_image',
            field=models.ImageField(blank=True, default='', max_length=400, null=True, upload_to='Product_Cat/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgs',
            field=models.ImageField(blank=True, default='', max_length=400, null=True, upload_to='Product_imgs/'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Sc_image',
            field=models.ImageField(blank=True, default='', max_length=400, null=True, upload_to='Product_sub_cat'),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='profile',
            field=models.ImageField(blank=True, default='', max_length=400, null=True, upload_to='UserProfile/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='profile',
            field=models.ImageField(blank=True, default='', max_length=400, null=True, upload_to='VenderProfile/'),
        ),
    ]
