# Generated by Django 3.1.7 on 2021-03-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_auto_20210320_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='venders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor'),
        ),
        migrations.AddField(
            model_name='offer',
            name='venders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.sub_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='venders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='venders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor'),
        ),
    ]
