# Generated by Django 3.1.7 on 2021-03-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_auto_20210321_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
