# Generated by Django 3.1.7 on 2021-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_usersdata_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Shop_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_contact_em',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_contact_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_img',
            field=models.ImageField(blank=True, default='', max_length=400, null=True, upload_to='VenderProfile/'),
        ),
    ]
