# Generated by Django 3.1.7 on 2021-03-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_auto_20210322_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('Order_amount', models.CharField(default='', max_length=100)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='owner_order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('product', models.CharField(default='', max_length=300)),
                ('qty', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.usersdata')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor')),
            ],
        ),
    ]
