# Generated by Django 3.1.7 on 2021-03-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_owner_order_table_owner_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(default='', upload_to='orders/')),
                ('product', models.CharField(default='', max_length=300)),
                ('qty', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.usersdata')),
            ],
        ),
    ]
