# Generated by Django 3.1.7 on 2021-03-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0010_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models_Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField(default='')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('usersData', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.usersdata')),
                ('vendors', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor')),
            ],
        ),
    ]
