# Generated by Django 3.1.7 on 2021-03-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_models_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks_of_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(default='1', max_length=20)),
                ('feedback', models.TextField()),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.product')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.usersdata')),
            ],
        ),
    ]
