# Generated by Django 3.1.7 on 2021-03-22 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_feedbacks_of_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChat_IDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default='', max_length=100)),
                ('usersData', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.usersdata')),
                ('vendors', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='models_chats',
            name='ch_ids',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.modelchat_ids'),
        ),
    ]
