# Generated by Django 3.1.7 on 2021-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0016_owner_order_table_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
    ]
