# Generated by Django 3.1.7 on 2021-04-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0020_remove_product_color_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='P_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
