# Generated by Django 3.2.7 on 2021-10-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0021_auto_20210410_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
