# Generated by Django 3.2.7 on 2021-10-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0022_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='forgot_ans',
            field=models.CharField(default='', max_length=100, verbose_name='Write Something Which Help You To Change Your Password'),
        ),
    ]
